import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import TopLoaderBar from '@/components/TopLoaderBar'
import Searchbar from '@/components/Searchbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopLoaderBar/>
        <Navbar />
        <Searchbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
