import Menubar from "./components/Menubar"

export const metadata = {
    title: 'DASHBOARD | E Commerce',
    description: 'Generated by create next app',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return <>
        <Menubar />
        {children}
    </>
}